##############################################
# Mach alerter configuration                 #
##############################################
[alerter]
# Only print the warning log if the alerter is disabled,
# Otherwise the alerts will be sent to the Mach AVS Operator
# Optional, default value: false
enable = false
# The JSONRPC endpoint of Mach AVS Operator
url = "http://127.0.0.1:8901"

##############################################
# Mach validator configuration               #
##############################################
[validator]
# Validate mode: "unsafe", "safe", "strict"
#
# "unsafe": Don't validate block, return ok directly.
# "safe": Validate block, return ok regardless of whether it's right or wrong.
# "strict": Validate block, return the execution result.
#
# Optional, default value: "unsafe"
mode = "strict"

##############################################
# Mach fetcher configuration                 #
##############################################
[fetcher]
# The JSONRPC endpoint of Nitro node
#
# NOTE
# We need the Nitro node to enable `arbvalidator_validateMessageNumber` RPC if we use `safe` or `strict` validator mode
url = "https://dodochain-testnet-defensive.alt.technology"
# The interval (milliseconds) for fetching finalized/latest block of Nitro node
# Optional, default value: 4000ms
interval_ms = 4000

##############################################
# Mach l1 fetcher configuration              #
##############################################
[l1-fetcher]
# The JSONRPC endpoint of settlement layer node
l1_url = "https://arbitrum-sepolia.alt.technology"
# The bridge address on settlement layer
# You could get this address from https://rollup-info.altlayer.io/public/orbit_demo_testnet
l1_bridge_address = "0x154c820EBaA49D169c33252ECc735623f9d49F82"
# The interval (milliseconds) for fetching data of settlement layer node
# Optional, default value: 4000ms
interval_ms = 4000

##############################################
# Mach scheduler configuration               #
##############################################
[scheduler]
# The timeout waiting for verify result.
# If it times out, the verify result will be checked again in the next tick.
# Optional, default value: 100ms
verify_timeout_ms = 100
# The timeout waiting for retry to validate.
# If it times out, the validation will be executed again in the next tick.
# Optional, default value: 10000ms
retry_wait_timout_ms = 10000

##############################################
# Mach prometheus configuration              #
##############################################
[prometheus]
# The TCP port of Prometheus exporter
# Optional, default value: 9715
port = 9715
# The HTTP URI path for fetching Prometheus metrics
# Optional, default value: "/metrics"
metrics_path = "/metrics"
# The indication if expose Prometheus exporter on all interfaces
# true: listen address = "0.0.0.0:port"
# false: listen address = "127.0.0.1:port"
# Optional, default value: false
external = false