{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mach-operator.secretsName" . }}
  labels:
    {{- include "mach-operator.labels" . | nindent 4 }}
stringData:
  bls_key.json: |
    {{ .Values.secrets.blsKeyJson }}
  blsKeyPassword: {{ .Values.secrets.blsKeyPassword }}
{{- end }}
