services:
  mach-generic-operator-node:
    env_file:
      - .env
    container_name: mach-avs-holesky-generic-operator
    image: ${MAIN_SERVICE_IMAGE}
    expose:
      - 8901
      - 9092
    networks:
      - alt-mach-operator-network
    volumes:
      - "${NODE_BLS_KEY_FILE_HOST}:/app/operator_keys/bls_key.json:readonly"
      - "${AVS_CONFIGS_PATH}:/app/configs:readonly"
      - "${NODE_DB_PATH_HOST}:/data/operator/db:rw"
    restart: unless-stopped
    command:
      - --avs-config=/app/configs/avs_configs.json
  
  mach-generic-operator-proxy:
    env_file:
      - .env
    container_name: mach-avs-holesky-generic-operator-proxy
    image: ${MAIN_SERVICE_PROXY_IMAGE}
    expose:
      - 8902
    networks:
      - alt-mach-operator-network
    volumes:
      - "${AVS_CONFIGS_PATH}:/app/configs:readonly"
    restart: unless-stopped
    depends_on:
      - mach-generic-operator-node
    command:
      - --config=/app/configs/operator_proxy.yaml
      - --avs-config=/app/configs/avs_configs.json

  mach-op-sepolia-operator-verifier:
    env_file:
      - .env
    container_name: mach-avs-holesky-op-sepolia-operator-verifier
    image: ${MACH_VERIFIER_IMAGE}
    expose:
      - 9094
    networks:
      - alt-mach-operator-network
    volumes:
      - "${MACH_CONFIG_ROOT_PATH}/op_sepolia/:/app/:readonly"
    command:
      - --config=/app/mach-config.toml
      - --genesis-config=/app/genesis.json
    depends_on:
      - mach-generic-operator-node
      - mach-generic-operator-proxy
    restart: unless-stopped

  mach-xterio-testnet-operator-verifier:
    env_file:
      - .env
    container_name: mach-avs-holesky-xterio-testnet-operator-verifier
    image: ${MACH_VERIFIER_IMAGE}
    expose:
      - 9095
    networks:
      - alt-mach-operator-network
    volumes:
      - "${MACH_CONFIG_ROOT_PATH}/xterio_testnet/:/app/:readonly"
    command:
      - --config=/app/mach-config.toml
      - --genesis-config=/app/genesis.json
    depends_on:
      - mach-generic-operator-node
      - mach-generic-operator-proxy
    restart: unless-stopped

  node-exporter:
    profiles: [monitoring]
    image: prom/node-exporter:latest
    container_name: ${MONITOR_NODE_EXPORTER_NAME}
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - alt-mach-operator-network

  prometheus:
    profiles: [monitoring]
    image: prom/prometheus:latest
    env_file:
      - .env
    container_name: ${MONITOR_PROMETHEUS_NAME}
    restart: unless-stopped
    volumes:
      - "../../../resources/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - alt-mach-operator-network

  grafana:
    profiles: [monitoring]
    image: grafana/grafana
    container_name: ${MONITOR_GRAFANA_NAME}
    ports:
      - "13000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "../../../resources/monitoring/grafana:/etc/grafana/provisioning/datasources"
      - "../../../resources/monitoring/dashboards:/etc/grafana/provisioning/dashboards"
      - "../../../resources/monitoring/alerting:/etc/grafana/provisioning/alerting"
    networks:
      - alt-mach-operator-network

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  alt-mach-operator-network:
    name: ${NETWORK_NAME}
