secrets:
  enabled: true
  blsKeyJson: |
    {}
  blsKeyPassword: ""
node:
  env:
    - name: OPERATOR_PRODUCTION
      value: "false"
    - name: ETH_RPC_URL
      value: "https://ethereum-holesky-rpc.publicnode.com"
    - name: ETH_WS_URL
      value: "wss://ethereum-holesky-rpc.publicnode.com"
    - name: OPERATOR_ECDSA_ADDRESS
      value: ""
    - name: AGGREGATOR_JSONRPC_SERVER_URL
      value: "https://op-sepolia-aggregator-1.alt.technology"
    - name: AVS_REGISTRY_COORDINATOR_ADDRESS
      value: "0x1eA7D160d325B289bF981e0D7aB6Bf3261a0FFf2"
    - name: OPERATOR_STATE_RETRIEVER_ADDRESS
      value: "0xBE1c904525910fdB49dB33b4960DF9aC9f603dC7"
    - name: LAYER1_CHAIN_ID
      value: "17000"
    - name: LAYER2_CHAIN_ID
      value: "11155420"
configs:
  genesis.json: |
    {
      "config": {
        "chainId": 11155420,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "muirGlacierBlock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "arrowGlacierBlock": 0,
        "grayGlacierBlock": 0,
        "mergeNetsplitBlock": 0,
        "bedrockBlock": 0,
        "regolithTime": 0,
        "terminalTotalDifficulty": 0,
        "terminalTotalDifficultyPassed": true,
        "optimism": {
          "eip1559Elasticity": 6,
          "eip1559Denominator": 50
        }
      },
      "nonce": "0x0",
      "timestamp": "0x64d6dbac",
      "extraData": "0x424544524f434b",
      "gasLimit": "0x1c9c380",
      "difficulty": "0x0",
      "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "coinbase": "0x4200000000000000000000000000000000000011",
      "alloc": {},
      "number": "0x0",
      "gasUsed": "0x0",
      "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "baseFeePerGas": "0x3b9aca00"
    }
  mach-config.toml: |
    ##############################################
    # Mach alerter configuration                 #
    ##############################################
    [alerter]
    # Only print the warning log if the alerter is disabled,
    # Otherwise the alerts will be sent to the Mach AVS Operator
    # Optional, default value: false
    enable = true
    # The JSONRPC endpoint of Mach AVS Operator
    url = "http://127.0.0.1:8901"

    ##############################################
    # Mach validator configuration               #
    ##############################################
    [validator]
    # Validate mode: "unsafe", "safe", "strict"
    #
    # "unsafe": Don't execute EVM, return ok directly.
    # "safe": Execute EVM ，return ok regardless of whether it's right or wrong.
    # "strict": Execute EVM, return the execution result.
    #
    # Optional, default value: "unsafe"
    mode = "unsafe"
    # The rate limit of rpc request
    # Optional, default value: 100ms
    rpc_rate_ms = 100

    ##############################################
    # Mach fetcher configuration                 #
    ##############################################
    [fetcher]
    # The JSONRPC endpoint of Optimism node
    url = "https://sepolia.optimism.io/"
    # The interval (milliseconds) for fetching finalized/latest block of Optimism node
    # Optional, default value: 1000ms
    interval_ms = 4000

    ##############################################
    # Mach scheduler configuration               #
    ##############################################
    [scheduler]
    # The timeout waiting for verify result.
    # If it times out, the verify result will be checked again in the next tick.
    # Optional, default value: 100ms
    verify_timeout_ms = 100

    ##############################################
    # Mach prometheus configuration              #
    ##############################################
    [prometheus]
    # The TCP port of Prometheus exporter
    # Optional, default value: 9715
    port = 9715
    # The HTTP URI path for fetching Prometheus metrics
    # Optional, default value: "/metrics"
    metrics_path = "/metrics"
    # The indication if expose Prometheus exporter on all interfaces
    # true: listen address = "0.0.0.0:port"
    # false: listen address = "127.0.0.1:port"
    # Optional, default value: false
    external = true